language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 7.1

env:
  # latest stable:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  fast_finish: true

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
